version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            sudo apt-get install git wget          
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

workflows:
  main:
    jobs:
      - build
